name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        scheme: [macOS, visionOS]
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: System Info
        run: |
          uname -a
          xcodebuild -version

      - name: Build
        run: xcodebuild -project Ensemble.xcodeproj -scheme ${{ matrix.scheme }} CODE_SIGNING_ALLOWED=NO
